# Generated by Django 5.2.7 on 2025-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_options_women_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[('0', 'Черновик'), ('1', 'Опубликовано')], default=('1', 'Опубликовано')),
        ),
    ]
