# Generated by Django 5.2.7 on 2025-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0006_alter_category_options_alter_husband_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads")),
            ],
        ),
    ]
