# Generated by Django 5.2.7 on 2025-11-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0007_uploadfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadFile",
        ),
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d",
                verbose_name="Фото",
            ),
        ),
    ]
